### ISSUE TITLE
[DOCS] Enhance README with Collaborators Sectio

### ISSUE THREAD

**Issue by rubemfsv** [rubemfsv/Github-Explorer-Mobile-Clean-Architecture#4]
The README file serves as a crucial source of information for our project. To foster transparency and acknowledge the valuable contributions from our team members and collaborators, we should add a dedicated "Collaborators" section to the README. This small but meaningful addition reflects our commitment to open collaboration and transparency.

**Goals:**

- In the end of the README, create a new section within the README that showcases our project's collaborators.
- Recognize and give credit to the individuals who have contributed to the project's success.
- Provide acknowledgment information for collaborators (e.g., https://github.com/all-contributors/all-contributors, https://github.com/testing-library/testing-library-docs).
- Foster a sense of community and collaboration among the project.

**Tasks:**

1. Edit the README file to include a new section titled "Collaborators" (you can adjust the "Branches and contributions" section)
2. Compile a list of project collaborators, including their names and informations.
3. Ensure that the new section is formatted consistently with the rest of the README, maintaining readability and clarity.
4. Verify that all information presented in the "Collaborators" section is up to date and accurate.
5. Consider including any additional details or content that would enrich the collaborator profiles.

Guidelines:

- Be respectful and accurate in the descriptions and acknowledgments of collaborators.
- Keep the "Collaborators" section organized and easy to read.

**Comment by manviii27** [comment]
Hi @rubemfsv , can I work on this issue?
