### ISSUE TITLE
[DOCS] Add MIT License and Update README.md

### ISSUE THREAD

**Issue by rubemfsv** [rubemfsv/Github-Explorer-Mobile-Clean-Architecture#7]
**Description**

Please add the MIT License to our project repository and update the README.md file accordingly.

**Expected Behavior**

The MIT License should be added to the project repository, and the README.md file should be modified to include information about the license, including a license badge and any relevant details about the license terms.

**Actual Behavior**

Currently, our project does not have a license specified, which can create confusion about how the code can be used and shared. It's essential to add a clear and permissive license to ensure that others can use the code with legal certainty.

**Screenshots (if applicable)**

N/A

**Additional Information**

By adding the MIT License and updating the README.md, we will make it clear to potential users and contributors how they can use, modify, and distribute the code. This action aligns with open-source best practices and ensures legal compliance. Please follow standard procedures for adding the MIT License to the repository. [Example](https://github.com/eslint/eslint/blob/main/LICENSE).

**Comment by bkpecho** [comment]
Hello. I would like to work on this one.

**Comment by rubemfsv** [comment]
@bkpecho ok! Follow the best practices for commits
